spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/go_to_work_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog.xml

  jpa:
    show-sql: true
    open-in-view: false

  application:
    name: telegram-bot

  profiles:
    active: dev
logging:
  level:
    org.zalando.logbook: TRACE

server:
  port: 8081

bot:
  token: ${BOT_TOKEN:8326413347:AAGF078sIq646SQafkaBgz1Eht9PQnciqAQ}
  username: ${BOT_USERNAME:go_to_work1_bot}
  url: http://go-to-work:8080/api/routes