spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/go_to_work_db
    username: postgres
    password: postgres

#  liquibase:
#    change-log: classpath:db/changelog.xml

#  jpa:
#    show-sql: true
#    open-in-view: false

app:
  dadata:
    api-key: f0d7b7fbc70c8fd3baaa7a534539ef03c265e412
    url: https://suggestions.dadata.ru/suggestions/api/4_1/rs/suggest/address
  twogis:
    api-key: fceafaa7-8334-4910-9f22-5064da2f2489
    url: https://routing.api.2gis.com