spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/go_to_work_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  liquibase:
    change-log: classpath:db/changelog.xml

  jpa:
    show-sql: true
    open-in-view: false

server:
  port: 8080

app:
  dadata:
    api-key: ${DADATA_API_KEY:f0d7b7fbc70c8fd3baaa7a534539ef03c265e412}
    url: https://suggestions.dadata.ru/suggestions/api/4_1/rs/suggest/address
  graphhooper:
    api-key: ${GRAPHHOOPER_API_KEY:443b290d-37b9-495d-b3bd-688e8e28ff1e}
    url: https://graphhopper.com/api/1/route