spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/go_to_work_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog.xml

  jpa:
    show-sql: true
    open-in-view: false

  application:
    name: go-to-work-core

  profiles:
    active: ${SPRING_APPLICATION_PROFILE:prod}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
#    consumer:
#      group-id: go-to-work-core-service
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: "*"
#        spring.json.type.mapping: kafkaMessage:org.maxsid.work.dto.KafkaMessage
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    org.zalando.logbook: TRACE

server:
  port: 8080

app:
  dadata:
    api-key: ${DADATA_API_KEY:f0d7b7fbc70c8fd3baaa7a534539ef03c265e412}
    url: https://suggestions.dadata.ru/suggestions/api/4_1/rs/suggest/address
  graphhooper:
    api-key: ${GRAPHHOOPER_API_KEY:443b290d-37b9-495d-b3bd-688e8e28ff1e}
    url: https://graphhopper.com/api/1/route