name: Deploy to Server

on:
  push:
    branches: [ main, master ]

env:
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/your-app-name
  DOCKER_TAG: latest

jobs:
  build-and-push-images:
    name: Build & Push images to DockerHub
    runs-on: ubuntu-latest
    needs: [detect-changes]
    steps:
      - uses: actions/checkout@v4
      - name: Login to private Docker registry (max1994)
        uses: docker/login-action@v3
        with:
          registry: max1994
          username: ${{ secrets.DOCKER_PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_PRIVATE_REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.7.0

      - name: GoToWorkCore Build and Push to max1994
        if: ${{ needs.detect-changes.outputs.go-to-work == 'true' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./GoToWorkCore/Dockerfile
          push: true
          tags: max1994/gotoworkparent-go-to-work:latest    

      - name: Telegram Bot Build and Push to max1994
        if: ${{ needs.detect-changes.outputs.telegram-bot == 'true' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./TelegramBot/Dockerfile
          push: true
          tags: overregistry.ru/overmoney-telegram-bot   

